language: elixir

cache:
  - apt
  - directories:
      - ~/.mongodb

elixir:
  - 1.3
  - 1.4
  - 1.5

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g mongodb-version-manager@1.0.6
  - m use $MONGOVERSION
  - mkdir db

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - (cd examples/simple; mix deps.get)

before_script:
  - sudo service mongodb stop
  - export PATH=$(m path):$PATH
  - mongod --fork --logpath mongo.log --dbpath db

script:
  - mix test
  - (cd examples/simple; mix test)

after_script:
  - mix deps.get --only docs
  - mix inch.report
  - MIX_ENV=test mix coveralls.travis

env:
  matrix:
    - MONGOVERSION=2.4.14
    - MONGOVERSION=2.6.12
    - MONGOVERSION=3.0.12
    - MONGOVERSION=3.2.10
